<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="RevitHotLoader2025">
      <HintPath>..\..\deploy\RevitHotLoader2025.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
